server:
  port: 8080
spring:
  application:
    name: "accounts"
  rabbitmq:
    host: "localhost"
    port: 5672
    username: "guest"
    password: "guest"
  datasource:
    url: jdbc:mysql://localhost:3306/school_db
    username: {cipher}41de8234702bf0f5bdfe88c70ea5074ccd9cf2ad66b25db4c420c1a8c3dc34b5
    password: {cipher}3c83fa5ee72dc9f2e73e8a281b306b7e9a332c760ab3251ee327080739415502  
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  sql:
    init:
      mode: always

management:
  endpoints:
    web:
      exposure:
        include: "*"      

build:
  version: "1.0"

accounts:
  message: "Hey, welcome to EazyBank accounts related prod APIs."
  contactDetails:
    name: "Reine Aishwarya - Product Owner"
    email: "{cipher}f83ac5a34ba5f4657ae8e863c063c1b69efb4d23d0c431eb134f8d1b3ed0823dee0a4b627d091455b4c6600353a3682c"
  onCallSupport:
    - (453) 392-4829
    - (236) 203-0384
