server:
  port: 8081
spring:  
  rabbitmq:
    host: "localhost"
    port: 5672
    username: "guest"
    password: "guest"
  datasource:
    url: jdbc:mysql://localhost:3306/school_db
    username: root
    password: root  
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  sql:
    init:
      mode: always
eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/
management:
  endpoints:
    web:
      exposure:
        include: "*"
logging:
  level:
    org:
    springframework:
      security: ${SPRING_SECURITY_LOG_LEVEL:DEBUG}
      oauth2: ${SPRING_SECURITY_LOG_LEVEL:DEBUG}
  pattern:
    console: ${LOGPATTERN_CONSOLE:%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n}              
build:
  version: "4.0"
accounts:
  message: "Welcome to EazyBank accounts related QA APIs"
  contactDetails:
    name: "Smitha Ray - QA Lead"
    email: "smitha@eazybank.com"
  onCallSupport:
    - (666) 265-3765
    - (666) 734-8371
